### ISSUE TITLE
Narrow Down API Options:

### ISSUE THREAD

**Issue by KashCodes** [Sly-Is-The-Fox/Sly-Is-The-Fox#2]
# Narrow Down API Options:

We need to run JSON request to as many API's as we can before class at 7PM Wednesday 1/27. By doing this we should be able to identify what information we can pull from the promise object JSON's.  This will help us narrow down if we CAN use Superhero's or if we need to pivot to a different API, with a similar theme. Remember, our goal is to be able to pull an easily identifiable name and corresponding image.  Then be able to run the name through a Wikipedia search later in the Memory Card game so they can open it up as a subject and learn more about it.  

## To Do: 
- [x] Try to Fetch, .Ajax, etc... different API's and convert them to JSON's. 
- [x] See if you are able to pull an image and name to be used for the game cards and wiki searches. 
- [x] Share the things you are successful with and the things you are not.  Commit to your sandbox branch.
- [x] If unsuccessful, share the error messages you are getting as well. 
- [x] Try to see if you can fix any peer's unsuccessful attempts if possible.  
- [x] Please add comments to this issue with your successful and unsuccessful attempts. Or comment and push your commits. 
- [x] Update slack with a quick "Hey added something to the GitHub issue" so everyone is notified and knows to look. 
- [x] If you can share more details in slack that's great, not needed though. I'll try and hop in and try help/attempt/duplicate as much as I can.  

----------------------

### "Some" API Lists We Can Try and Connect To:  (Note: I didn't put these in any particular order...)
> - [x] https://developer.marvel.com/docs   -  Marvel
> - [x] https://superheroapi.com/  -  SuperHeroAPI
> - [ ] https://www.mediawiki.org/wiki/API:Main_page   -  Wikipedia
> - [ ] https://github.com/AniList/ApiV2-GraphQL-Docs  -  AniList API (Anime List)
> - [x] https://myanimelist.net/clubs.php?cid=13727  -  MyAnimeList 
> - [x] https://ghibliapi.herokuapp.com/  -  Studio Ghibli 
> - [ ] https://github.com/harvardartmuseums/api-docs  -  Harvard Art Museum API
> - [x] http://www.dnd5eapi.co/  -  Dungeons & Dragons (DND)
> - [ ] https://magicthegathering.io/  -  Magic The Gathering (Card Game - Defnitely should have images)
> - [x] https://pokeapi.co/ - Pokemon API
> - [x] https://pokemontcg.io/  -  Pokemon API
> - [ ] https://api.nasa.gov/  -  NASA (includes imagery)
> - [ ] http://stapi.co/  -  Star Trek
> - [ ] https://anapioficeandfire.com/  -  Game of Thrones 
> - [ ] https://the-one-api.dev/  -  Lord of the Rings

Other API's I found by Googling. No idea if they use Cors or not. 
> - [ ] https://developer.imdb.com/  -  IMBD API
> - [ ] https://www.themoviedb.org/documentation/api  - Movie Data 
> - [ ] https://rapidapi.com/rapidapi/api/movie-database-imdb-alternative  -  Movie Database/ IMBD Alternative 
> - [ ] http://www.tvmaze.com/api  -  TV Data
> - [ ] https://api.thetvdb.com/swagger  -  TV Data 
> - [ ] https://rapidapi.com/apigeek/api/google-search3   -  Google search 
> - [ ] https://rapidapi.com/omgvamp/api/hearthstone   -   Hearthstone (Big Online Video Game)
> - [ ] https://rapidapi.com/chewett/api/pokemon-go1  -  Pokemon Go 
> - [ ] https://dog.ceo/dog-api/  -  Dog Pics w/ Dog Breeds List 
> - [ ] https://developer.riotgames.com/  -  Riot Games (Video Game Devs - Creates Multiple Big Games) 
> - [ ] https://develop.battle.net/  -  Blizzard Games (Video Game Devs - Creates Multiple Big Games) 

Original GitHub List TJ Gaves Us:
> - [ ] https://github.com/public-apis/public-apis

**Comment by bstanfield1992** [comment]
Ghibli has no pictures.

**Comment by bstanfield1992** [comment]
Both Superheroes and Marvel use CORS.

**Comment by bstanfield1992** [comment]
DND no pictures.

**Comment by bstanfield1992** [comment]
The two pokemon APIs are pretty good. No key needed and both have images.

**Comment by KashCodes** [comment]
Decided on using:
https://randomfox.ca/floof/
https://opentdb.com/api_config.php

The concept changed to a fox themed trivia game.
